# Generated by Django 4.2.7 on 2023-11-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=40)),
                ('apellido_alumno', models.CharField(max_length=70)),
                ('telefono_alumno', models.CharField(max_length=10)),
                ('email_alumno', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Materias',
            },
        ),
    ]
