# Generated by Django 4.2.7 on 2023-11-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=40)),
                ('apellido_alumno', models.CharField(max_length=70)),
                ('telefono_alumno', models.CharField(max_length=10)),
                ('email_alumno', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
    ]
